services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dono
      POSTGRES_PASSWORD: example
      POSTGRES_DB: default_database
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    container_name: backend
    command: node script_back.js
    volumes:
      - ./backend:/app
    depends_on:
      - database
    ports:
      - 3000:3000

  # front:
  #   image: nginx:latest
  #   container_name: front
  #   volumes:
  #     - ./src/public:/usr/share/nginx/html
  #   ports:
  #     - "3001:80"


